[package]
name = "KMI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
